# CircleCI configuration file
version: 2.1

jobs:
  # Job one with a unique name
  insall_dependecy:
    docker:
     - image: cimg/base:2022.05
    steps:
      - run: docker run --rm \
            -u "$(id -u):$(id -g)" \
            -v $(pwd):/var/www/html \
            -w /var/www/html \
            laravelsail/php81-composer:latest \
            composer install --ignore-platform-reqs
  # Job two with a unique name
  run_tests:
    docker:
     - image: cimg/base:2022.05
        
    steps:
      - run: ./vendor/bin/sail artisan test

workflows:
  # Name of workflow
  hello_and_goodbye:
    # List of jobs that will run
    jobs:
      - insall_dependecy
      - run_tests