version: "2.1"
orbs:
  slack: circleci/slack@4.9.3

jobs:
  build:
    executor: docker
    docker:
      - image: cimg/php:8.0-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: product
    working_directory: ~/laravel
    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt-get update
            sudo apt-get install -y mysql-client
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit

  notify:
    executor: docker
    docker:
      - image: 'cimg/base:stable'
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - slack/notify:
          event: fail
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1

workflows:
  send-notification:
    jobs:
      - build
      - notify:
          context: slack-secrets
