version: 2.1
jobs:
  build:
    docker:
      - image: circleci/php:8.0-fpm-buster
      - run: sudo service docker restart
    working_directory: ~/repo
    steps:
      - checkout
      - run: docker version
      - run: composer install
      - run:
          name: Start Sail containers
          command: ./vendor/bin/sail up -d
      - run:
          name: Run Tests
          command: ./vendor/bin/sail test
      - store_test_results:
          path: tests/TestResults.xml
      - store_artifacts:
          path: tests/coverage
