version: 2.1

jobs:
  test:
    docker:
      - image: circleci/php:8.0-browsers
    working_directory: ~/project
    steps:
      - checkout
      - run: cp .env.example .env
      - run: composer install --no-interaction
      - run: php artisan key:generate
      - run: ./vendor/bin/sail up -d
      - run: ./vendor/bin/sail artisan migrate --force
      - run: ./vendor/bin/sail test

workflows:
  build-and-test:
    jobs:
      - test
