version: 2

jobs:
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8.0-browsers
      - image: circleci/mysql
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: No
          MYSQL_USER: admin
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: product

    working_directory: ~/laravel

    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
      - run: sudo composer self-update

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      - run:
          name: Setup Laravel stuffs
          command: |
            php artisan migrate --force
      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  notify_deploy:
    jobs:
      - build