version: "2.1"
orbs:
  slack: circleci/slack@4.9.3
jobs:
  build:
    docker:
      - image: cimg/php:8.0-browsers
      - image: cimg/mysql:8.0
        environment:
          MYSQL_ALLOW_EMPTY_PASSWORD: yes
          MYSQL_USER: admin
          MYSQL_PASSWORD: password
          MYSQL_DATABASE: product
    working_directory: ~/laravel
    steps:
      - checkout
      - run:
          name: Install PHP exts
          command: |
            sudo docker-php-ext-install zip
            sudo docker-php-ext-install pdo_mysql
            sudo apt-get update
            sudo apt-get install -y mysql-client
      - run: sudo composer self-update
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: composer install -n --prefer-dist

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}
      - run: cp .env.example .env
      - run: php artisan key:generate
      - run: ./vendor/bin/phpunit
    when: on_fail
  notify:
    docker:
      - image: "cimg/base:stable"
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD # context / project UI env-var reference
    steps:
      # Remove the `event: pass` notification as it is not necessary
      # Add a `when` statement to only send the notification if the build fails
      - slack/notify:
          event: fail
          template: basic_fail_1
        when: on_fail
workflows:
  send-build-notifications:
    jobs:
      # Specify that the `notify` job should only run after the `build` job completes
      - build
      - notify:
          context: slack-secrets
        requires:
          - build
