version: 2.1

jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: circleci/php:7.4-fpm-buster
    steps:
      - checkout
      - run:
          name: Start Sail containers
          command: |
            ./vendor/bin/sail up -d

workflows:
  build:
    jobs:
      - build
