version: 2.1

jobs:
  build:
    working_directory: ~/app
    docker:
      - image: circleci/php:7.4-fpm-buster
      - image: circleci/mysql:5.7
        environment:
          MYSQL_DATABASE: test
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
    steps:
      - checkout
      - run: curl -fsSL https://get.docker.com -o get-docker.sh
      - run: sudo sh get-docker.sh
      # - run: sudo service docker start
      - run:
          name: Install Dependencies
          command: |
            curl -s https://raw.githubusercontent.com/laravel/sail/v1.1.0/bin/sail \
              --output sail
            chmod +x sail
            ./sail up -d
      - run:
          name: Run Tests
          command: |
            ./sail artisan test
      - run:
          name: Stop Docker containers
          command: |
            ./sail down

workflows:
  build:
    jobs:
      - build
